name: CI

on: [push]

jobs:

  build:
    runs-on: ubuntu-20.04

    steps:
    - name: checkout
      uses: actions/checkout@v2

    - name: Install rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: 1.44.1
        override: true
        components: clippy

    - name: Install libpurple
      run: |
        bash -c '\
          sudo apt-get update \
          && sudo apt-get install -y intltool libglib2.0-dev libnss3-dev \
                                     libltdl3-dev libxml2-dev libxml-parser-perl \
                                     libsqlite3-dev libidn11-dev \
          && hg clone https://keep.imfreedom.org/pidgin/pidgin \
          && cd pidgin \
          && hg up v2.13.0 \
          && ./autogen.sh \
                  --prefix=/usr \
                  --disable-nm \
                  --without-x --disable-gtkspell --disable-gstreamer \
                  --disable-vv --disable-meanwhile --disable-avahi \
                  --disable-dbus --disable-tcl --disable-gtkui --disable-perl \
          && make -C libpurple -j$(nproc) \
          && sudo make -C libpurple install \
        '

    - name: Run cargo check
      uses: actions-rs/cargo@v1
      with:
        command: check

    - name: Run cargo clippy
      uses: actions-rs/cargo@v1
      with:
        command: clippy
        args: --all-targets -- -D warnings

  fmt:
    runs-on: ubuntu-20.04
    steps:
    - name: checkout
      uses: actions/checkout@v2

    - name: Install rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: 1.44.1
        override: true
        components: rustfmt

    - name: Check format
      run: cargo fmt -- --check
